---
- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  listen: restart nginx
  tags: always

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  listen: reload nginx
  tags: always
