---
- name: Install git on linux hosts
  hosts: linux
  become: true
  tasks:
    - name: Install git
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: true
        cache_valid_time: 3600

# concepts:
# - become
# - playbook
# - tasks
