---
- name: Setup linux webservers
  hosts: linux
  become: true
  tasks:
    - name: Include nginx role
      ansible.builtin.include_role:
        name: my-nginx
      tags:
        - install
        - config

# concepts:
# - become
# - group_vars
# - handlers
# - loop
# - roles
# - tags
# - tasks
# - templates
# - when
# - diff
# - check_mode
